import { useEffect, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import api from '../lib/api';
import { toast } from '../lib/toast';

type SettingItem = { key: string; enabled: boolean };
type Policy = { categories: SettingItem[]; actors: SettingItem[] };

const descriptions: Record<string, string> = {
  AUTH: 'Login, logout, MFA, OTP, password, and identity events.',
  AUTHZ: 'Permission checks, denied access, and validation failures.',
  CREATE: 'New records and resources created by an actor.',
  UPDATE: 'Changes to existing records and fields.',
  DELETE: 'Deleted and soft-deleted records.',
  READ: 'Business data access, views, and searches.',
  EXPORT: 'Exports, downloads, reports, and printed records.',
  TRANSITION: 'Status and workflow transitions.',
  FINANCIAL: 'Payments, refunds, invoices, and subscription billing.',
  SECURITY: 'Security controls and security-sensitive activity.',
  ADMIN: 'Administrative operations and privileged actions.',
  SYSTEM: 'System and platform activity.',
  INTEGRATION: 'Webhooks and external integrations.',
  FILE: 'Uploads, downloads, and file operations.',
  CONFIG: 'Settings, feature flags, and configuration changes.',
};

const labels: Record<string, string> = {
  USER: 'Customer / User',
  ADMIN: 'Administrator',
  CSR: 'Customer Service (CSR)',
  WEB_EDITOR: 'Web Editor',
  DESIGNER: 'Designer',
  AUTHOR: 'Author',
  SERVICE: 'Application Service',
  SYSTEM: 'System',
  SCHEDULED_JOB: 'Scheduled Job',
  API_CLIENT: 'API Client',
  WEBHOOK: 'Webhook',
  AI_AGENT: 'AI Agent',
  FINDER: 'Finder / Anonymous Visitor',
  UNKNOWN: 'Unknown Actor',
};

function Toggle({ enabled, onToggle, disabled }: { enabled: boolean; onToggle: () => void; disabled: boolean }) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={enabled}
      disabled={disabled}
      onClick={onToggle}
      className={`relative inline-flex h-6 w-11 shrink-0 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 disabled:opacity-50 ${enabled ? 'bg-primary-600' : 'bg-gray-300'}`}
    >
      <span className={`inline-block h-5 w-5 transform rounded-full bg-white shadow transition-transform ${enabled ? 'translate-x-5' : 'translate-x-0.5'}`} />
    </button>
  );
}

export default function AuditSettings() {
  const [policy, setPolicy] = useState<Policy | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState<string | null>(null);

  const fetchPolicy = () => {
    setLoading(true);
    api.get('/admin/audit/settings')
      .then((res) => setPolicy(res.data.data))
      .catch(() => toast.error('Failed to load audit settings'))
      .finally(() => setLoading(false));
  };

  useEffect(fetchPolicy, []);

  const toggle = async (kind: 'category' | 'actor', item: SettingItem) => {
    const id = `${kind}:${item.key}`;
    setSaving(id);
    try {
      await api.put(`/admin/audit/settings/${kind}/${item.key}`, { enabled: !item.enabled });
      setPolicy((current) => current && {
        ...current,
        [kind === 'category' ? 'categories' : 'actors']: (kind === 'category' ? current.categories : current.actors)
          .map((entry) => entry.key === item.key ? { ...entry, enabled: !entry.enabled } : entry),
      });
      toast.success('Audit setting updated');
    } catch {
      toast.error('Failed to update audit setting');
    } finally {
      setSaving(null);
    }
  };

  const renderGroup = (kind: 'category' | 'actor', items: SettingItem[]) => (
    <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
      <div className="px-5 py-4 border-b border-gray-100">
        <h2 className="font-semibold text-gray-900">{kind === 'category' ? 'Event Categories' : 'Actor Types'}</h2>
        <p className="text-xs text-gray-500 mt-1">Disable only when there is a documented compliance or operational reason.</p>
      </div>
      <div className="divide-y divide-gray-100">
        {items.map((item) => (
          <div key={item.key} className="px-5 py-4 flex items-center justify-between gap-4">
            <div>
              <p className="text-sm font-medium text-gray-900">{kind === 'actor' ? labels[item.key] || item.key : item.key}</p>
              <p className="text-xs text-gray-500 mt-0.5">{kind === 'category' ? descriptions[item.key] : `Events generated by ${labels[item.key] || item.key}.`}</p>
            </div>
            <Toggle enabled={item.enabled} disabled={saving === `${kind}:${item.key}`} onToggle={() => toggle(kind, item)} />
          </div>
        ))}
      </div>
    </div>
  );

  return (
    <div className="space-y-6">
      <div className="flex items-start gap-3">
        <span className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-50 text-primary-600"><ShieldCheck className="h-5 w-5" /></span>
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Audit Settings</h1>
          <p className="text-sm text-gray-500 mt-1">Control enterprise audit logging by event category and actor type. Changes are themselves audited.</p>
        </div>
      </div>
      {loading || !policy ? <div className="bg-white rounded-xl border border-gray-200 p-10 text-center text-gray-500">Loading audit settings...</div> : (
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
          {renderGroup('category', policy.categories)}
          {renderGroup('actor', policy.actors)}
        </div>
      )}
    </div>
  );
}
