packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@medusajs/telemetry': true
  '@scarf/scarf': true
  esbuild: true
  mongodb-memory-server: true
  msgpackr-extract: true
  protobufjs: true
publicHoistPattern:
  - '*@medusajs/*'
  - '@tanstack/react-query'
  - 'react-i18next'
  - 'react-router-dom'
