export { connectDatabase, disconnectDatabase, mongoose } from './connection';

export { User, type IUserDocument } from './models/User';
export { Pet, type IPetDocument, generatePetId } from './models/Pet';
export { Tag, type ITagDocument } from './models/Tag';
export { Product, type IProductDocument } from './models/Product';
export { Order, type IOrderDocument } from './models/Order';
export { LocationEvent, type ILocationEventDocument } from './models/LocationEvent';
export { FinderScan, type IFinderScanDocument } from './models/FinderScan';
export { Notification, type INotificationDocument } from './models/Notification';
export { SiteContent, type ISiteContentDocument } from './models/SiteContent';
export { Setting, type ISettingDocument } from './models/Setting';
export { FeatureFlag, type IFeatureFlagDocument } from './models/FeatureFlag';
export { AuditLog, type IAuditLogDocument } from './models/AuditLog';
export { Role, type IRoleDocument } from './models/Role';
export { PermissionGroup, type IPermissionGroupDocument } from './models/PermissionGroup';
export { Permission, type IPermissionDocument } from './models/Permission';
export { PermissionScope, type IPermissionScopeDocument } from './models/PermissionScope';
export { UserRole, type IUserRoleDocument } from './models/UserRole';
export { RolePermission, type IRolePermissionDocument } from './models/RolePermission';
