export { connectDatabase, disconnectDatabase, mongoose } from './connection';

export { User, type IUserDocument } from './models/User';
export { Pet, type IPetDocument, generatePetId } from './models/Pet';
export { Tag, type ITagDocument } from './models/Tag';
export { VerificationToken, type IVerificationTokenDocument } from './models/VerificationToken';
export { Product, type IProductDocument } from './models/Product';
export { Cart, type ICartDocument } from './models/Cart';
export { Order, type IOrderDocument } from './models/Order';
export { LocationEvent, type ILocationEventDocument } from './models/LocationEvent';
export { FinderScan, type IFinderScanDocument } from './models/FinderScan';
export { Notification, type INotificationDocument } from './models/Notification';
export { SiteContent, type ISiteContentDocument } from './models/SiteContent';
export { Setting, type ISettingDocument } from './models/Setting';
export { FeatureFlag, type IFeatureFlagDocument } from './models/FeatureFlag';
export { AuditLog, type IAuditLogDocument } from './models/AuditLog';
export { Role, type IRoleDocument } from './models/Role';
export { PermissionGroup, type IPermissionGroupDocument } from './models/PermissionGroup';
export { Permission, type IPermissionDocument } from './models/Permission';
export { PermissionScope, type IPermissionScopeDocument } from './models/PermissionScope';
export { UserRole, type IUserRoleDocument } from './models/UserRole';
export { RolePermission, type IRolePermissionDocument } from './models/RolePermission';
export { CmsPage, type ICmsPageDocument, type ICmsPageSection } from './models/CmsPage';
export { CmsPageVersion, type ICmsPageVersionDocument } from './models/CmsPageVersion';
export { CmsNavigation, type ICmsNavigationDocument, type ICmsNavigationItem } from './models/CmsNavigation';
export { CmsFooter, type ICmsFooterDocument, type ICmsFooterGroup, type ICmsFooterLink } from './models/CmsFooter';
export { CmsMedia, type ICmsMediaDocument } from './models/CmsMedia';
export { CmsAnnouncement, type ICmsAnnouncementDocument } from './models/CmsAnnouncement';
export { CmsRedirect, type ICmsRedirectDocument } from './models/CmsRedirect';
