export { renderVerificationEmail } from './verification-email';
export { renderPhoneOtpMessage } from './phone-otp';
export { renderWelcomeEmail } from './welcome';
export { renderPasswordResetEmail } from './password-reset';
export { renderPasswordChangedEmail } from './password-changed';
export { renderOrderConfirmationEmail } from './order-confirmation';
export { renderShippingNotificationEmail } from './shipping-notification';
export { renderPetFoundEmail } from './pet-found';
export { renderAccountStatusEmail } from './account-status';
export { renderLoginNotificationEmail } from './login-notification';
export { renderLoginOtpEmail } from './mfa-otp';
export { renderRefundProcessingEmail } from './refund-processing';
export { renderRefundSettledEmail } from './refund-settled';
export { renderRefundFailedEmail } from './refund-failed';
export { renderGuardianWelcomeEmail } from './guardian-welcome';
export { renderTierUpgradeEmail } from './guardian-tier-upgrade';
export { renderMonthlySummaryEmail } from './guardian-monthly-summary';
export { renderPawRewardsReminderEmail } from './guardian-pawrewards-reminder';
export { renderGuardianBirthdayEmail } from './guardian-birthday';
export { renderGuardianAnniversaryEmail } from './guardian-anniversary';
export { renderGuardianRenewalReminderEmail } from './guardian-renewal-reminder';
export { renderPurchasePointsEmail } from './guardian-purchase-points';
export { renderGoldWelcomeEmail } from './gold-welcome';
// ─── New templates (inline email extractions) ───
export { renderNewOrderAlertEmail, renderOrderCancelledAlertEmail, renderRefundFailedAlertEmail, renderSupportRequestAlertEmail } from './admin-alert';
export { renderOrderStatusEmail } from './order-status';
export { renderSubscriptionWelcomeEmail, renderSubscriptionReminderEmail, renderGracePeriodReminderEmail, renderPaymentFailureEmail, renderGracePeriodStartedEmail, renderPaymentRetrySuccessEmail } from './subscription-lifecycle';
export { renderReferralRewardEmail } from './referral-reward';
export { renderTierDowngradeWarningEmail } from './tier-downgrade-warning';
export { renderPetBirthdayEmail } from './pet-birthday';
export { renderPetAnniversaryEmail } from './pet-anniversary';
export { renderEmergencyEscalationEmail } from './emergency-escalation';
export { renderGenericNotificationEmail } from './generic-notification';
export { renderLowStockAlertEmail } from './low-stock-alert';
export { renderSubscriptionWelcomeEmail as renderSubscriptionWelcomeTemplateEmail } from './subscription-welcome';
export { renderInvoiceOtpEmail as renderInvoiceOtpTemplateEmail } from './invoice-otp';
export { renderCancellationEmail } from './cancellation';
